mysite/bills/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/splogs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addlog/', views.addlog, name='addlog'),
    url(r'^viewlog/', views.viewlog, name='viewlog'),
    url(r'^pay/', views.pay, name='pay'),
    url(r'^histpmt/', views.histpmt, name='histpmt'),
]

mysite/splogs/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime, date
from dateutil import tz

# Create your models here.

class Logs(models.Model):
    date=models.DateField(default=date.today())
    name=models.CharField(max_length=100)
    product=models.CharField(max_length=300)
    price=models.FloatField(default=0.)
    cleared=models.BooleanField(default=False)

    def __unicode__(self):              # __unicode__ on Python 2
        to_zone = tz.gettz('America/New_York')
        return "{}\t{}\t{}".format(self.date, self.name.strip().replace(' ','_'), self.price)
        #return "{}\t{}\t{}\t{:.2f}"%(self.date.astimezone(to_zone).strftime('%Y-%m-%d'), self.name, self.product, self.price)
class Pmt(models.Model):
    date=models.DateField(default=date.today())
    fromN=models.CharField(max_length=100)
    toN=models.CharField(max_length=100)
    amount=models.FloatField(default=0.)

    def __unicode__(self):              # __unicode__ on Python 2
        to_zone = tz.gettz('America/New_York')
        return "{}\t{}\t{}".format(self.date, self.fromN.strip().replace(' ','_'),  self.toN.strip().replace(' ','_'), self.amount)
        #return "{}\t{}\t{}\t{:.2f}"%(self.date.astimezone(to_zone).strftime('%Y-%m-%d'), self.name, self.product, self.amount)

mysite/splogs/forms.py
from splogs.models import Logs, Pmt
from django.forms import ModelForm
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class LogsForm(ModelForm):
    class Meta:
        model = Logs
        fields = ['date', 'name', 'product', 'price']
        widgets = { 'date': DateInput(), }

class PmtForm(ModelForm):
    class Meta:
        model = Pmt
        fields = ['date', 'fromN', 'toN', 'amount']
        widgets = { 'date': DateInput(), }

mysite/splogs/views.py
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render, render_to_response, redirect
from .models import Logs, Pmt
from .forms import LogsForm, PmtForm
from django.http import HttpResponse
from django.template import RequestContext, loader
from datetime import datetime
from django.contrib.auth import authenticate, login, logout
from compAve import SharedPurchase
from django.contrib.auth.models import User, Group
# Create your views here.
def getName(byName):
    members=[str(u.first_name.lower()) for u in User.objects.all()]
    if byName.lower() in members: return byName.lower()
    for n in members:
        if byName.lower().find(n)>-1:
            return n
    return byName.lower()
def index(request):
    if not request.user.is_authenticated: return redirect('/')
    if len(request.user.first_name) > 0: uName=request.user.first_name
    else: uName=request.user.username
    t = loader.get_template('index.html')
    c = RequestContext(request, {'login_logout': "Logout", 'username': uName, 'user': request.user})
    return HttpResponse(t.render(c), content_type="application/xhtml+xml")
@csrf_protect
def addlog(request):
    if not request.user.is_authenticated: return redirect('/')
    form = LogsForm()
    if request.POST:
        form = LogsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    if len(request.user.first_name) > 0: uName=request.user.first_name
    else: uName=request.user.username
    return render(request,'form.html', {'today': datetime.today().strftime("%Y-%m-%d"), 'form': form, 'name': getName(byName=str(uName)).title(), 'login_logout': "Logout", 'username': uName, 'user': request.user})
    #return render_to_response('addlog.html',{ 'form': form },RequestContext(request))

def viewlog(request):
    if not request.user.is_authenticated: return redirect('/')
    group = Group.objects.get(name='home_members')
    members=[str(u.first_name.lower()) for u in group.user_set.all()]
    a=SharedPurchase(initWithPurchase=Logs.objects.all(), andPayment=Pmt.objects.all(), andMembers=members)
    text=str(a)+'\n'#+'-'+'\n'
    summary=text
    rawData=Logs.objects.order_by('-date')#[s.split() for strList]
    for s in rawData:
        s.name=getName(byName=s.name).title()
    #text.replace('\n','</br>')
    #return HttpResponse("<pre>%s</pre>"%text)
    if len(request.user.first_name) > 0: uName=request.user.first_name
    else: uName=request.user.username
    t = loader.get_template('view.html')
    c = RequestContext(request, {'sum': '{:.2f}'.format(a.sum), 'ave': '{:.2f}'.format(a.ave), 'indiv': a.getList(), 'rawData': rawData, 'login_logout': "Logout", 'username': uName, 'user': request.user})
    return HttpResponse(t.render(c))#, content_type="application/xhtml+xml")

@csrf_protect
def pay(request):
    if not request.user.is_authenticated: return redirect('/')
    form = PmtForm()
    if request.POST:
        form = PmtForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    if len(request.user.first_name) > 0: uName=request.user.first_name
    else: uName=request.user.username
    return render(request,'pmtform.html', {'today': datetime.today().strftime("%Y-%m-%d"), 'form': form, 'name': getName(byName=str(uName)).title(), 'login_logout': "Logout", 'username': uName, 'user': request.user})

def histpmt(request):
    if not request.user.is_authenticated: return redirect('/')
    rawData=Pmt.objects.order_by('-date')
    for s in rawData:
        s.fromN=getName(byName=s.fromN).title()
        s.toN=getName(byName=s.toN).title()
    if len(request.user.first_name) > 0: uName=request.user.first_name
    else: uName=request.user.username
    t = loader.get_template('viewHistPmt.html')
    c = RequestContext(request, {'rawData': rawData, 'login_logout': "Logout", 'username': uName, 'user': request.user})
    return HttpResponse(t.render(c), content_type="application/xhtml+xml")

mysite/splogs/templates/base.html
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
<!-- Loading Bootstrap --> <!-- Loading Flat UI -->
<!--<link rel="stylesheet" type="text/css" charset="utf-8" href="/static/dist/css/vendor/bootstrap/css/bootstrap.min.css"/>-->
<link rel="stylesheet" type="text/css" href="/static/dist/css/flat-ui.min.css"/>
<link rel="stylesheet" href="/static/css/base.css" type="text/css" />
<head>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <!--<script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js"></script>-->
    <!--<script src="/static/js/jquery.ui.touch-punch.min.js"></script>-->
    <!--<script src="/static/js/jquery.mobile.custom.min.js"></script>-->
<style>

</style>
    <title>{% block title %}{% endblock %}</title>
</head>
  <body>
  <div id="mySidenav" class="sidenav disable-selection">
    <a style="cursor:pointer;" class="closebtn" onclick="closeNav()">&times;</a>
    <div class="sidenav-content">
    <a style="cursor:pointer;" onclick="window.location.href='/'">Main Menu</a>
    <a style="cursor:pointer;" onclick="window.location.href='/splogs/addlog'">Submit Purchases</a>
    <a style="cursor:pointer;" onclick="window.location.href='/splogs/viewlog'">View summary</a>
    <a style="cursor:pointer;" onclick="window.location.href='/splogs/pay'">Submit payment</a>
    <a style="cursor:pointer;" onclick="window.location.href='/splogs/histpmt'">Payment history</a>
    <a style="cursor:pointer;" onclick="window.location.href='/bills'">View bills</a>
    <!--<hr/>-->
    {% if username %}
    <div class="strike"><span>{{ username }}</span></div>
    {% else %}
    <hr style="border-color: #818181"/>
    {% endif %}
    {% if user.is_superuser %}
        <a style="cursor:pointer;" onclick="window.location.href='/admin'">Admin</a>
    {% else %}
        <a style="cursor:pointer;" onclick="window.location.href='/account'">Account</a>
    {% endif %}
    <a style="cursor:pointer;" onclick="window.location.href='/logout'">{{ login_logout }}</a>
    </div>
    <div class="disable-selection" style="position:absolute;width:250px;bottom:0;left:5px;font-size:10px">By LFu</div>
  </div>

  <div id="lmenu">
  <ul id="lmenu">
      <li id="lmenu" class="disable-selection" style="font-size:30px;cursor:pointer;" onclick="openNav()"> &#9776;</li>
  </ul>
  </div>

  <div id="main" style="transition: 0.5s">
  <h2 align="center" class="disable-selection">{% block pagetitle %}{% endblock %}</h2>
  <hr/>

  {% block content %}{% endblock %}
  </div>

  <script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "275px";
        if ($(window).width() > 600) {
            document.getElementById("main").style.marginLeft = "275px";
        }
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
        document.getElementById("main").style.marginLeft = "0";
    }
    $(document).ready(function(){
        $(window).bind('click',function(){
            closeNav()
        });
        $('#mySidenav').bind('click',function(event){
            event.stopPropagation();
        });
        $('#lmenu').bind('click',function(event){
            event.stopPropagation();
        });
    });
  </script>
  </body>
</html>

mysite/splogs/templates/change_password.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block pagetitle %}Login{% endblock %}
{% block logstate %}{{ log_btn }}{% endblock %}
{% block content %}

<div align="center" class="disable-selection">
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>
</div>

{% endblock %}

mysite/splogs/templates/form.html
{% extends "base.html" %}
{% block title %}Purchases{% endblock %}

{% block pagetitle %}Purchases{% endblock %}
{% block logstate %}{{ log_btn }}{% endblock %}
{% block content %}

<div align="center" class="disable-selection">
<form method="POST">
{% csrf_token %}
    <table align="center" style="border-collapse:separate;border-spacing: 10px 5px;">
        <tr>
            <!--<th align="right"><label for="id_date">Date:</label></th>-->
            <th><input class="form-control" id="id_date" name="date" type="date" value="{{ today }}" required /></th>
        </tr>
        <tr>
            <!--<th align="right"><label for="id_name">Name:</label></th>-->
            <th><input class="form-control" placeholder="Name" id="id_name" maxlength="100" name="name" type="text" value="{{name}}" required /></th>
        </tr>
        <tr>
            <!--<th align="right"><label for="id_product">Product:</label></th>-->
            <th><input class="form-control" placeholder="Product" id="id_product" maxlength="300" name="product" type="text" required /></th>
        </tr>
        <tr>
            <!--<th align="right"><label for="id_price">Price:</label></th>-->
            <th><input class="form-control" placeholder="Price" id="id_price" name="price" step="any" type="number" value="" required /></th>
        </tr>
    </table>
    <br>
    <input class="btn btn-default" type="submit" value="Submit"/>

</form>
</div>

{% endblock %}

mysite/splogs/templates/formGeneric.html
{% extends "base.html" %}
{% block title %}Add item{% endblock %}

{% block pagetitle %}Purchases{% endblock %}
{% block logstate %}{{ log_btn }}{% endblock %}
{% block content %}

<div align="center" class="disable-selection">
<form method="POST">{% csrf_token %} 
{{ form.as_p }}
<input type="submit" value="submit">
</form>
</div>

{% endblock %}

mysite/splogs/templates/index.html
{% extends "base.html" %}
{% block title %}Main Menu{% endblock %}

{% block pagetitle %}Main Menu{% endblock %}
{% block logstate %}{{ log_btn }}{% endblock %}
{% block content %}

  <div align="center" class="disable-selection">
      <div class="row">
        <a class="btn btn-default btn-custome" style="width: 250px;" href="/splogs/addlog">Submit a purchase</a><br/>
      </div>
      <div class="row">
        <a class="btn btn-default btn-custome" href="/splogs/viewlog">View summary</a><br/>
      </div>
      <div class="row">
        <a class="btn btn-default btn-custome" href="/splogs/pay">Submit payment</a><br/>
      </div>
      <div class="row">
        <a class="btn btn-default btn-custome" href="/splogs/histpmt">Payment history</a><br/>
      </div>
      <div class="row">
        <a class="btn btn-default btn-custome" href="/bills">View bills</a><br/>
      </div>
  </div>

{% endblock %}

mysite/splogs/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block pagetitle %}Login{% endblock %}
{% block logstate %}{{ log_btn }}{% endblock %}
{% block content %}

<div align="center" class="disable-selection">
<form method="POST">
{% csrf_token %}
    <table align="center" style="border-collapse:separate;border-spacing: 10px 5px;">
        {% if msg %}
        <td align="center"><font color="red">{{msg}}</font></td>
        {% endif %}
        <tr>
            <th><input class="form-control" placeholder="User Name" id="id_user" maxlength="100" name="user" type="text" required /></th>
        </tr>
        <tr>
            <!--<th align="right"><label for="id_price">Price:</label></th>-->
            <th><input class="form-control" placeholder="Password" id="id_password" name="password" type="password" required /></th>
        </tr>
    </table>
    <br>
    <input class="btn btn-default" type="submit" value="Login"/>

</form>
</div>

{% endblock %}

mysite/splogs/templates/pmtform.html
{% extends "base.html" %}
{% block title %}Payment{% endblock %}

{% block pagetitle %}Payment{% endblock %}
{% block logstate %}{{ log_btn }}{% endblock %}
{% block content %}

<div align="center" class="disable-selection">
<form method="POST">
{% csrf_token %}
    <table align="center" style="border-collapse:separate;border-spacing: 10px 5px;">
        <tr>
            <th>
                <input class="form-control" id="id_date" name="date" type="date" value="{{ today }}" required />
            </th>
        </tr>
        <tr>
            <th>
                <input class="form-control" placeholder="From" id="id_fromN" maxlength="100" name="fromN" type="text" value="{{name}}"  required />
            </th>
        </tr>
        <tr>
            <th>
                <input class="form-control" placeholder="To" id="id_toN" maxlength="100" name="toN" type="text" required />
            </th>
        </tr>
        <tr>
            <th>
                <input class="form-control" placeholder="Amount" id="id_amount" name="amount" step="any" type="number" value="" required />
            </th>
        </tr>
    </table>
    <br>
    <!--{{ form.as_p }}-->
    <input class="btn btn-default" type="submit" value="Submit"/>

</form>
</div>

{% endblock %}

mysite/splogs/templates/view.html
{% extends "base.html" %}
{% block title %}Report{% endblock %}

{% block pagetitle %}Summary{% endblock %}
{% block logstate %}{{ log_btn }}{% endblock %}
{% block content %}

    <table style="border-spacing: 0px 0;"  align="center" class="disable-selection">
        <tr>
            <td width="80" align="left">Total</td>
            <td width="80" align="right">{{ sum }}</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #ddd;" align="left">Ave</td>
            <td style="border-bottom: 1px solid #ddd;" align="right">{{ ave }}</td>
        </tr>
        {% for n, p in indiv %}
        <tr>
            <td align="left">{{ n }}</td>
            <td align="right">{{ p }}</td>
        </tr>
        {% endfor %}
    </table>
    <hr/>
    <table style="border-collapse:separate;border-spacing: 5px 0;text-align:center;"  align="center" class="disable-selection">
        <tr>
            <th>Date</th>
            <th>Name</th>
            <th>Product</th>
            <th>Price</th>
        </tr>
        {% for item in rawData %}
        {% if not item.cleared %}
        <tr>
            <td>{{ item.date }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.product }}</td>
            <td>{{ item.price|floatformat:2 }}</td>
        </tr>
        {% else %}
        <tr style="color:#BDC3C7">
            <td>{{ item.date }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.product }}</td>
            <td>{{ item.price|floatformat:2 }}</td>
        </tr>
        {% endif %}
        {% endfor %}
    </table>

{% endblock %}

mysite/splogs/templates/viewHistPmt.html
{% extends "base.html" %}
{% block title %}Payment history{% endblock %}

{% block pagetitle %}Payment history{% endblock %}
{% block logstate %}{{ log_btn }}{% endblock %}
{% block content %}

    <table style="border-collapse:separate;border-spacing: 10px 0;"  align="center" class="disable-selection">
        <tr>
            <th>Date</th>
            <th>From</th>
            <th>To</th>
            <th>Amount</th>
        </tr>
        {% for item in rawData %}
        <tr>
            <td>{{ item.date }}</td>
            <td>{{ item.fromN }}</td>
            <td>{{ item.toN }}</td>
            <td>{{ item.amount|floatformat:2 }}</td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}